"""A deterministic, network-free `CodeGenerator` for tests and credential-free local runs.

No concrete network provider (OpenAI, Anthropic, ...) is implemented in
this milestone: this project has no LLM API credentials or configuration
in place (confirmed by inspection of `TaraSettings` and `.env.example`),
and this milestone's own instructions are explicit that a provider
adapter should only be built once credentials already exist.
`FakeCodeGenerator` is what makes the rest of the generation stage --
and every test in this package -- runnable without either.
"""
from __future__ import annotations

from collections.abc import Callable
from typing import Any

from tara.fusion.token_budget import approximate_token_count
from tara.generation.models import GeneratedCode, Prompt
from tara.interfaces.code_generator import CodeGenerator

_DEFAULT_RESPONSE_TEXT = "# Generated by FakeCodeGenerator\n# No real LLM was called."


class FakeCodeGenerator(CodeGenerator):
    """Returns a canned or derived response instead of calling any real LLM provider.

    `response_text` may be a fixed string or a `Prompt -> str` callable,
    so a test can assert the response reflects what was actually
    assembled into the prompt (mirrors `DeterministicFakeEmbedder` in
    `tests/retrieval/conftest.py` and `_FakeRetriever` in
    `tests/retrieval/test_orchestrator.py`: a small, fully controllable
    test double rather than an opaque one). `call_count` and
    `last_prompt` are exposed for the same reason `_FakeRetriever`
    exposes `call_count`: asserting a caller invoked this exactly once,
    with the expected prompt.
    """

    def __init__(
        self,
        response_text: str | Callable[[Prompt], str] | None = None,
        model: str = "fake-model",
        prompt_tokens: int | None = None,
        completion_tokens: int | None = None,
        estimate_tokens: bool = True,
        latency_ms: float = 0.0,
        metadata: dict[str, Any] | None = None,
        raises: Exception | None = None,
    ) -> None:
        """Construct the fake.

        Args:
            response_text: Fixed text to return, or a callable deriving
                text from the `Prompt` it was invoked with. Defaults to
                a fixed placeholder string when omitted.
            model: The model identifier `GeneratedCode.model` reports.
            prompt_tokens: Fixed `GeneratedCode.prompt_tokens` value.
                Takes priority over `estimate_tokens` when given.
            completion_tokens: Fixed `GeneratedCode.completion_tokens`
                value. Takes priority over `estimate_tokens` when given.
            estimate_tokens: When True (default) and the corresponding
                `prompt_tokens`/`completion_tokens` argument was not
                given, a plausible count is computed via
                `tara.fusion.token_budget.approximate_token_count` over
                the relevant text, so tests exercising "token counts
                were captured" get a sensible non-None default without
                specifying one. Set False to report `None` instead
                (simulating a provider that does not report usage),
                unless the corresponding `*_tokens` argument was given
                explicitly.
            latency_ms: `GeneratedCode.latency_ms` to report. Fixed
                rather than measured (unlike a real provider) so tests
                asserting on it are deterministic.
            metadata: `GeneratedCode.metadata` to report. Defaults to
                `{"provider": "fake"}` when omitted.
            raises: If set, `generate` raises this instead of returning
                a result -- for testing failure-path handling.
        """
        self._response_text = response_text
        self._model = model
        self._prompt_tokens = prompt_tokens
        self._completion_tokens = completion_tokens
        self._estimate_tokens = estimate_tokens
        self._latency_ms = latency_ms
        self._metadata = metadata
        self._raises = raises
        self.call_count = 0
        self.last_prompt: Prompt | None = None

    def generate(self, prompt: Prompt) -> GeneratedCode:
        """See `CodeGenerator.generate`. Never makes a network call."""
        self.call_count += 1
        self.last_prompt = prompt

        if self._raises is not None:
            raise self._raises

        text = self._resolve_response_text(prompt)

        prompt_text = prompt.system + prompt.user
        return GeneratedCode(
            text=text,
            model=self._model,
            prompt_tokens=self._resolve_token_count(self._prompt_tokens, prompt_text),
            completion_tokens=self._resolve_token_count(self._completion_tokens, text),
            latency_ms=self._latency_ms,
            metadata=self._metadata if self._metadata is not None else {"provider": "fake"},
        )

    def _resolve_response_text(self, prompt: Prompt) -> str:
        if self._response_text is None:
            return _DEFAULT_RESPONSE_TEXT
        if callable(self._response_text):
            return self._response_text(prompt)
        return self._response_text

    def _resolve_token_count(self, explicit: int | None, text: str) -> int | None:
        if explicit is not None:
            return explicit
        if self._estimate_tokens:
            return approximate_token_count(text)
        return None
